language: node_js
sudo: required
services:
- docker
before_install:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --no-include-email --region us-east-2)
install:
- docker build -t basket .
script:
- docker run -it -p 8000:8000 basket npm test
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJAUQER3J3AKWB3CQ
  secret_access_key:
    secure: AWS_SECRET_ACCESS_KEY
  region: us-east-1
  app: thesis2
  env: test
  bucket_name: elasticbeanstalk-us-east-1-767596259046
env:
  matrix:
    secure: bnqRI3zY7zaAl6wUp3AWN0a9pu4AyaBY+EWMc69a3MOZneeCTqFIdhTubIncONQa8MRt/iLhHgzEYM5qHNaRMsv2MgpfeiRO11U3TILwxbi0Z5RrwaQFUwMxNZhPunp96u/UPbnz/LX4zwW+p80EiAfg8NEs1ho9lAKIJFkqMiRXSBl+ktOK4IhCrvOOqflaGZUj1SZ/cIZO6vGxpam+DFuPOB8RU/uwJPQ4YG0LFDwc2TD0CvayXtXhxuixcYdli0yeC1uGiA7cl5cfT2CVz8O2WbklbIp+WRKPqeRdl6qUx3zFLMlpqFNVAtYUfaOc09ho05pUx3yYz5WJnZvkY8ZgNZWeQGPznPq0GeRg7aLHdvdTlaXnIGvnTN6l5BGAT0/b/2jQpoMZGCVQJxJvmUQtob+zu1nI9mRjEelYqDvirEDXa9SgbrvBgaGFbN2wNnab6C5wNSr374TAozQc2bfB7C06o3TO4oe49iNLKtrmHo1KJD2CpJl7qFjQDlX7tzH6ry3bgEImxuyNVBrm15INrrPVdVZIHcbdZr776H/XXgFQBOONxoZfPpPezN/wpEiRg+TLa835XhXRVhJ5QnFx1uGdOtDzVfYQKasiCqfWOJm3JY7Vco1BiRreHR28Mnre0K5A3hISjPoYB1x1H5iX1BdotFKk0TiC0URyxGY=
