language: node_js
sudo: required
services:
- docker

before_install:
  - docker --version  # document the version travis is using
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - eval $(aws ecr get-login --no-include-email --region us-east-2) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  #- docker pull 767596259046.dkr.ecr.us-east-2.amazonaws.com/basket-starter:latest
  - pip install awsebcli --upgrade --user
  - eb deploy
install:
- docker build -t basket .

script:
 - docker run -it -p 8000:8000 basket npm test

deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJAUQER3J3AKWB3CQ
  secret_access_key:
    secure: "qTptL3AdFm8NkPs0d1BGcB+RfKoM3r7PYy/BGcdAzyevUe32EQX6b4PjmrgJT4D/wyXMaKAXhSIgx9mswXpDAV7VOrSh/CAP0snmEKNCOuoD9hUAbGV52G8xWMjczWnFMzpZJmXVXcTb3zhSXZSALIYU8EBLOYc3FYHouok9lv2Pwe+0H3JxA8vhdxh27giIZvzpKsOgkG2ZPjv5ux4aIEq3T708kIbFAcIoVOBepd3O3iys+bCY4HzdQciaWsp8oGfTnAx8pu2QdodJYJnvuqw2EgCAL0lGAwN02vZvZsjFIYAJJN4wqKO1WDYs7KyEchAAKc6d9zaZBwMPVJWzzXG/SWPCJpZJ3jmSpDqqBzRrWLi77lv+tOwnz/uGDxfjhD3hFGh4O3wZoZT8GhTtZc0ST0RLUZBq9jeR8K0ciBM3ZUKa6vNXK74xUMZoFY+c38MP/lyydP922F4lNcoRLjwHAaraLIt5yYZAzPTqQXeJtESQ1m2hbYOCWIjRO7kyeZua4e7GQdn4obzv5bN5LbiIn0js4Rzd/RzFZeiXty/FEz6kxy4lTAo0TWTMBEMkFIh+CSzMWcLtpFMfLraLg8BAoj1OG906ksIO8CL1xaP/h6snJGngOuaeqjfLLuhIKhvEw5kToWVQGHABqJ9v7UYeQaDOyE2jf/YUHw7x9B8="
  region: us-east-1
  app: thesis2
  env: thesistest
  bucket_name: elasticbeanstalk-us-east-1-767596259046