language: node_js
sudo: required
services:
- docker
before_install:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --no-include-email --region us-east-2)
install:
- docker build -t basket .
script:
- docker run -it -p 8000:8000 basket npm test
deploy:
  provider: elasticbeanstalk
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key:
    secure: ${AWS_SECRET_ACCESS_KEY}
  region: us-east-1
  app: basket
  env: basket-prod
  bucket_name: elasticbeanstalk-us-east-1-767596259046