sudo: required
services:
- docker
install:
- docker build -t basket .
script:
- npm run prodTest
deploy:
  provider: elasticbeanstalk
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key:
    secure: ${AWS_SECRET_ACCESS_KEY}
  region: us-east-1
  app: basket
  env: staging
  bucket_name: elasticbeanstalk-us-east-1-767596259046
  on:
    condition: "$TRAVIS_PULL_REQUEST == 'false'"